# Phase 1 ABM Configuration - Grounded in Bacolod, Lanao del Norte
# Context: 4th Income Class Municipality, ~1.5M SWM Budget (E.1)

model:
  total_households: 1000  # Total agents to simulate (approx 16% of 6,110)
  simulation_steps: 365   # 365 steps = 1 simulated year
  random_seed: 42

# Barangay Selection: Based on MENRO Interview (E.1)
# Weights: Based on 2020 Census (Total Pop of 7 Barangays: 14,992)
barangays:
  - name: "Poblacion Bacolod"
    type: "urban_center"
    weight: 0.434         # 6,507 pop / 14,992
    income_range: [0.65, 0.95]
    education_range: [0.60, 0.90]
    has_garbage_collection: true

  - name: "Liangan East"
    type: "urban_coastal"
    weight: 0.143         # 2,139 pop
    income_range: [0.50, 0.80]
    education_range: [0.45, 0.70]
    has_garbage_collection: true

  - name: "Esperanza"
    type: "urban_coastal"
    weight: 0.180         # 2,698 pop
    income_range: [0.40, 0.70]
    education_range: [0.40, 0.65]
    has_garbage_collection: true

  - name: "Binuni"
    type: "urban_coastal"
    weight: 0.127         # 1,910 pop
    income_range: [0.35, 0.60]
    education_range: [0.30, 0.55]
    has_garbage_collection: true

  - name: "Demologan"
    type: "urban_coastal"
    weight: 0.041         # 615 pop
    income_range: [0.30, 0.50]
    education_range: [0.25, 0.45]
    has_garbage_collection: true

  - name: "Mati"
    type: "rural_inland"  # "layo na kaayo" (E.1)
    weight: 0.038         # 570 pop (Adjusted from 615 for 14,992 total)
    income_range: [ 0.30, 0.50 ]
    education_range: [ 0.25, 0.45 ]
    has_garbage_collection: true

  - name: "Babalaya"
    type: "rural_inland"  # "layo na kaayo" (E.1)
    weight: 0.037         # 553 pop (Adjusted from 615 for 14,992 total)
    income_range: [ 0.30, 0.50 ]
    education_range: [ 0.25, 0.45 ]
    has_garbage_collection: true

# --- NEW: Parameters for Barangay-Level (Implementor) ---
barangay_parameters:
  # From Brgy. Liangan East Interview (E.2)
  base_barangay_budget: 30000 # ₱30k base budget for local programs

# --- UPDATED: Theory of Planned Behavior (TPB) Parameters ---
tpb_parameters:
  # FINAL CALIBRATION:
  # Make psychological benefits (A, SN) tiny and effort cost (PBC) massive.
  # This forces agents to be "rational" and non-compliant at baseline.
  attitude_weight: 0.10
  subjective_norm_weight: 0.10
  perceived_control_weight: 0.80  # The (1.0 - PBC) *effort cost* is now 80% of the decision

  # --- Agent Initialization Ranges ---
  # Final calibration to achieve ~10-15% baseline
  attitude_range: [0.0, 0.5]

  # CALIBRATION FIX:
  # The max PBC must be less than 1.0 to ensure there is *always* an effort cost.
  # A range of [0.3, 0.7] ensures even the "easiest" agent has an effort cost.
  perceived_control_range: [0.3, 0.7] # Changed from [0.5, 1.0]

  # Explicit SN ranges to match Appendix E (E.1 and E.2)
  initial_sn_range_non_liangan: [0.00, 0.00]
  initial_sn_range_liangan_east: [0.6, 0.7]

  # --- Dynamic Parameters ---
  sn_decay_rate: 0.95
  stochastic_epsilon_range: [-0.1, 0.1]
  utility_conversion_factor: 10

# --- NEW: PBC Penalties (Grounded in Appendix E) ---
# Used in HouseholdAgent.__init__ to set initial PBC
pbc_penalties:
  # "sako is expensive" (E.2)
  income_threshold: 0.40  # Agents below this income level (40%) suffer penalty
  income_penalty: 0.25    # 0.25 reduction in PBC

  # "layo na kaayo" (E.1)
  inland_penalty: 0.40    # 0.40 reduction in PBC for RURAL_INLAND type

# --- UPDATED: Economic Sensitivity Parameters ---
economic_sensitivity:
  base_incentive_sensitivity: 0.005 # Base utility multiplier per ₱
  base_fine_sensitivity: 0.012      # Fines have >2x the psychological impact
  income_effect_magnitude: 1.5      # Multiplier for income_effect (1.0 + 1.5 * (1-income))

# --- NEW: LGU Policy & Budget Translation (Supervisor Logic) ---
policy:
  # From MENRO Interview (E.1)
  total_lgu_annual_budget: 1500000
  track_incentive_budget: true

  # Fixed values from LGU Ordinance (Appendix D) or estimation
  base_incentive_php: 20   # Estimated ₱ value of an ecobrick / reward payout
  base_fine_php: 500       # Standard fine for 1st offense (from Appendix D)

  # Enforcement Budget -> P(Catch) Translation
  # Cost to hire "Eco-warriors" (E.1)
  enforcement_budget_for_max_p_catch: 1000000 # ₱1M budget = max enforcement
  max_p_catch_per_step: 0.05                  # Max 5% *daily* chance of being caught

  # Education Budget -> Boost Translation
  # Cost for "radio ads" and "IEC campaigns" (E.1)
  education_budget_for_max_boost: 250000      # ₱250k budget = max education effect
  education_max_boost_per_step: 0.001         # Max 0.001 *daily* boost to A and PBC

social_network:
  min_neighbors: 5
  max_neighbors: 15
  same_barangay_probability: 0.90 # Strong local peer effects